package fr.fiducial.signature.feature.clients.model;
// Generated Mar 1, 2019 11:53:13 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "signature_clients")
public class Adresse implements java.io.Serializable {

	private Long id;
	private Pays pays;
	private Personne personne;
	private Ville ville;
	private Integer num;
	private String ordreVoie;
	private String typeVoie;
	private String nomVoie;

	public Adresse() {
	}

	public Adresse(Pays pays, Personne personne, Ville ville, String nomVoie) {
		this.pays = pays;
		this.personne = personne;
		this.ville = ville;
		this.nomVoie = nomVoie;
	}

	public Adresse(Pays pays, Personne personne, Ville ville, Integer num, String ordreVoie, String typeVoie,
			String nomVoie) {
		this.pays = pays;
		this.personne = personne;
		this.ville = ville;
		this.num = num;
		this.ordreVoie = ordreVoie;
		this.typeVoie = typeVoie;
		this.nomVoie = nomVoie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pays", nullable = false)
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personne", nullable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ville", nullable = false)
	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	@Column(name = "num")
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Column(name = "ordre_voie", length = 5)
	public String getOrdreVoie() {
		return this.ordreVoie;
	}

	public void setOrdreVoie(String ordreVoie) {
		this.ordreVoie = ordreVoie;
	}

	@Column(name = "type_voie", length = 15)
	public String getTypeVoie() {
		return this.typeVoie;
	}

	public void setTypeVoie(String typeVoie) {
		this.typeVoie = typeVoie;
	}

	@Column(name = "nom_voie", nullable = false, length = 200)
	public String getNomVoie() {
		return this.nomVoie;
	}

	public void setNomVoie(String nomVoie) {
		this.nomVoie = nomVoie;
	}

}
