package fr.fiducial.signature.feature.clients.model;
// Generated Mar 1, 2019 11:53:13 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Capacite generated by hbm2java
 */
@Entity
@Table(name = "capacite", catalog = "signature_clients")
public class Capacite implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long id;
	private String capacite;

	public Capacite() {
	}

//	public Capacite(String capacite) {
//		this.capacite = capacite;
//	}


//
//	@Column(name = "id", unique = true, nullable = false)
//	public Long getId() {
//		return this.id;
//	}
//
//	public void setId(Long id) {
//		this.id = id;
//	}
//
//	@Column(name = "capacite", nullable = false, length = 200)
//	public String getCapacite() {
//		return this.capacite;
//	}
//
//	public void setCapacite(String capacite) {
//		this.capacite = capacite;
//	}

}
