package fr.fiducial.signature.feature.clients.model;
// Generated Mar 4, 2019 10:53:41 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Civilite generated by hbm2java
 */
@Entity
@Table(name = "civilite", catalog = "signature_clients")
public class Civilite implements java.io.Serializable {

    private Long id;
    private String civilite;
    private Set<Personne> personnes = new HashSet<Personne>(0);

    public Civilite() {
    }

    public Civilite(String civilite) {
        this.civilite = civilite;
    }

    public Civilite(String civilite, Set<Personne> personnes) {
        this.civilite = civilite;
        this.personnes = personnes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "civilite", nullable = false, length = 5)
    public String getCivilite() {
        return this.civilite;
    }

    public void setCivilite(String civilite) {
        this.civilite = civilite;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "civilite")
    public Set<Personne> getPersonnes() {
        return this.personnes;
    }

    public void setPersonnes(Set<Personne> personnes) {
        this.personnes = personnes;
    }
}
