package fr.fiducial.signature.feature.clients.model;
// Generated Mar 1, 2019 11:53:13 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DivorceRenduPar generated by hbm2java
 */
@Entity
@Table(name = "divorce_rendu_par", catalog = "signature_clients")
public class DivorceRenduPar implements java.io.Serializable {

	private Long id;
	private String renduPar;
	private Set<Evenement> evenements = new HashSet<Evenement>(0);

	public DivorceRenduPar() {
	}

	public DivorceRenduPar(String renduPar) {
		this.renduPar = renduPar;
	}

	public DivorceRenduPar(String renduPar, Set<Evenement> evenements) {
		this.renduPar = renduPar;
		this.evenements = evenements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "rendu_par", nullable = false, length = 200)
	public String getRenduPar() {
		return this.renduPar;
	}

	public void setRenduPar(String renduPar) {
		this.renduPar = renduPar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "divorceRenduPar")
	public Set<Evenement> getEvenements() {
		return this.evenements;
	}

	public void setEvenements(Set<Evenement> evenements) {
		this.evenements = evenements;
	}

}
