package fr.fiducial.signature.feature.clients.model;
// Generated Mar 1, 2019 11:53:13 AM by Hibernate Tools 5.2.11.Final

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evenement generated by hbm2java
 */
@Data
@NoArgsConstructor
//@JsonInclude(JsonInclude.Include.NON_NULL)
@Entity
@Table(name = "evenement", catalog = "signature_clients")
public class Evenement implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_divorce_rendu_par")
	private DivorceRenduPar divorceRenduPar;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_lieu_mariage")
	private LieuMariage lieuMariage;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_pays_mariage")
	private Pays pays;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_conjoint")
	private Personne conjoint;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_regime_mariage")
	private RegimeMariage regimeMariage;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_type_evenement")
	private TypeEvenement typeEvenement;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_type_PACS")
	private TypePacs typePacs;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_ville")
	private Ville ville;

	@Column(name = "est_pacse", nullable = false)
	private boolean estPacse;

	@Temporal(TemporalType.DATE)
	@Column(name = "date_evt", length = 10)
	private Date dateEvt;

	@Temporal(TemporalType.DATE)
	@Column(name = "jugement_divorce_date", length = 10)
	private Date jugementDivorceDate;

	@Column(name = "comment_separation", length = 200)
	private String commentSeparation;

	@Column(name = "ville_etrangere_mariage", length = 200)
	private String villeEtrangereMariage;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cause_rupture_PACS")
	private CauseRupturePacs causeRupturePacs;

	@Column(name = "notaire", length = 200)
	private String notaire;
}
