package fr.fiducial.signature.feature.clients.model;
// Generated Mar 1, 2019 11:53:13 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LieuMariage generated by hbm2java
 */
@Entity
@Table(name = "lieu_mariage", catalog = "signature_clients")
public class LieuMariage implements java.io.Serializable {

	private Long id;
	private String lieu;
	private Set<Evenement> evenements = new HashSet<Evenement>(0);

	public LieuMariage() {
	}

	public LieuMariage(String lieu) {
		this.lieu = lieu;
	}

	public LieuMariage(String lieu, Set<Evenement> evenements) {
		this.lieu = lieu;
		this.evenements = evenements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "lieu", nullable = false, length = 200)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lieuMariage")
	public Set<Evenement> getEvenements() {
		return this.evenements;
	}

	public void setEvenements(Set<Evenement> evenements) {
		this.evenements = evenements;
	}

}
