package fr.fiducial.signature.feature.clients.model;
// Generated Mar 1, 2019 11:53:13 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RegimeMariage generated by hbm2java
 */
@Entity
@Table(name = "regime_mariage", catalog = "signature_clients")
public class RegimeMariage implements java.io.Serializable {

	private Long id;
	private String type;
	private Set<Evenement> evenements = new HashSet<Evenement>(0);

	public RegimeMariage() {
	}

	public RegimeMariage(String type) {
		this.type = type;
	}

	public RegimeMariage(String type, Set<Evenement> evenements) {
		this.type = type;
		this.evenements = evenements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 200)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regimeMariage")
	public Set<Evenement> getEvenements() {
		return this.evenements;
	}

	public void setEvenements(Set<Evenement> evenements) {
		this.evenements = evenements;
	}

}
